development:
  adapter: postgresql
  encoding: unicode
  database: team_builder_dev
  pool: 5
  username: USERNAME
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: team_builder_test
  pool: 5
  username: USERNAME
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: team_builder
  pool: 5
  username: USERNAME
  password:

cucumber:
  <<: *test